**The conference/seminar has been supported by the Postgraduate Students Conference/Seminar Grants of the Research Grants Council, Hong Kong.**

# Step 0 Download the datatset & Extract Dog-Related Captions

In [ ]:
import pandas as pd
import requests
from io import BytesIO
import zipfile
import json

## Download the Flickr30k zip file
url = "https://cs.stanford.edu/people/karpathy/deepimagesent/flickr30k.zip"
response = requests.get(url)

## Extract the dataset.json file from the zip archive
with zipfile.ZipFile(BytesIO(response.content)) as z:
    with z.open('flickr30k/dataset.json') as f:
        data = json.load(f)

## Parse the JSON and filter captions containing "dog"
captions = []
for item in data['images']:
    for sentence in item['sentences']:
        if 'dog' in sentence['raw'].lower():
            captions.append(sentence['raw'])

## Save filtered captions to CSV file
pd.DataFrame(captions, columns=['caption']).to_csv('dog_captions.csv', index=False)

# Step 1 Import modules

Note: After running the code below, you should select "Restart session" under the "Runtime" menu, and then rerun the code.

In [ ]:
## English tagger
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
lemmatizer = WordNetLemmatizer()

## Install nltk packages (for tagging)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('omw-1.4')

## Install spellchecker
!pip install pyspellchecker==0.7.2
from spellchecker import SpellChecker
spell = SpellChecker()

## Glob files matching a specified pattern
import os
import glob
import csv

## Preprocess data
import re
from itertools import combinations

## Create a data frame
import pandas as pd

## Keyword analysis & semantic network analysis
!pip install apyori
!pip install mlxtend --upgrade
import networkx as nx
import operator
from sklearn.feature_extraction.text import TfidfVectorizer
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
from collections import Counter # frequency analysis

## Visualization for semantic network
import matplotlib.pyplot as plt
import matplotlib.colors as mcl
from matplotlib.colors import LinearSegmentedColormap
import numpy as np
from community import community_louvain

## Ignore warnings
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

## Read the dataset
df = pd.read_csv('dog_captions.csv')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

Collecting pyspellchecker==0.7.2
  Downloading pyspellchecker-0.7.2-py3-none-any.whl.metadata (9.4 kB)
Downloading pyspellchecker-0.7.2-py3-none-any.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 1.7 MB/s eta 0:00:00
Installing collected packages: pyspellchecker
Successfully installed pyspellchecker-0.7.2
Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=02a0249d610006f09dfb3dab6034c388f89bc3d9aa82febb58a2cfc9b855c2dd
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2
Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.16.3 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Collecting numpy>=2.3.5 (from mlxtend)
  Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pandas>=2.3.3 (from mlxtend)
  Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.7 MB/s eta 0:00:00
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: joblib>=1.5.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 21.6 MB/s eta 0:00:00
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 84.5 MB/s eta 0:00:00
Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 81.1 MB/s eta 0:00:00
Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 96.4 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 94.2 MB/s eta 0:00:00
Installing collected packages: numpy, pandas, scikit-learn, matplotlib, mlxtend
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.10.0
    Uninstalling matplotlib-3.10.0:
      Successfully uninstalled matplotlib-3.10.0
  Attempting uninstall: mlxtend
    Found existing installation: mlxtend 0.23.4
    Uninstalling mlxtend-0.23.4:
      Successfully uninstalled mlxtend-0.23.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.3 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.4.3 which is incompatible.
Successfully installed matplotlib-3.10.8 mlxtend-0.24.0 numpy-2.4.3 pandas-3.0.1 scikit-learn-1.8.0

# Step 2 Construct a corpus

In [ ]:
# @title 2-1

## Extract information (documents, comments, words) from corpus data

# Create an empty list
descriptions = [] # For dog descriptions
words = [] # For extracted content words

# Create a stopword list
stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(['dog', 'dogs'])

## Read in each description
with open('dog_captions.csv', mode='r', newline='', encoding='utf-8-sig') as file:
    reader = csv.reader(file)
    next(reader)  # skip header
    for row in reader:
        description = row[0]  # caption in the 1st row
        description = re.sub('[^A-Za-z ]',' ', description)
        description = re.sub(' +', ' ', description)
        description = description.lower()
        tokenized = nltk.word_tokenize(description)
        word_list = []

        for word, pos in nltk.pos_tag(tokenized):
            if pos[0] in ['V']:  # keep verbs
                lemma = lemmatizer.lemmatize(word, 'v')
                if (
                    len(word) > 2
                    and lemma not in stopwords
                    and lemma not in spell.unknown([lemma])
                ):
                    word_list.append(lemma)

        if len(word_list) != 0:
            descriptions.append(description)
            words.append(word_list)

In [ ]:
# @title 2-2

## Create a list containing all words (verbs in this case)
all_content_words = [j for i in words for j in i]
len(all_content_words)

11085

In [ ]:
# @title 2-3

## Count frequency
counter_unigram = Counter(all_content_words)
counter_unigram

Counter({'star': 20,
         'color': 71,
         'play': 859,
         'look': 316,
         'move': 16,
         'fight': 107,
         'sleep': 20,
         'sit': 241,
         'lay': 105,
         'tie': 18,
         'hold': 362,
         'lie': 64,
         'run': 2162,
         'surround': 31,
         'stand': 472,
         'turn': 11,
         'shake': 86,
         'fall': 43,
         'leap': 126,
         'jump': 500,
         'wear': 355,
         'grill': 18,
         'hotdogs': 1,
         'chase': 229,
         'prepare': 12,
         'catch': 399,
         'fly': 28,
         'try': 86,
         'get': 81,
         'make': 33,
         'carry': 246,
         'walk': 571,
         'crouch': 15,
         'attempt': 18,
         'throw': 56,
         'push': 11,
         'rest': 20,
         'open': 24,
         'grass': 1,
         'soak': 4,
         'stick': 22,
         'spray': 7,
         'mouth': 9,
         'watch': 84,
         'float': 9,
         'retrieve': 37,
         'tug': 14,
         'splash': 48,
         'fill': 17,
         'create': 3,
         'dry': 15,
         'snow': 4,
         'take': 63,
         'wash': 6,
         'size': 22,
         'secure': 1,
         'soap': 1,
         'give': 19,
         'bite': 121,
         'wrestle': 49,
         'bend': 8,
         'go': 27,
         'roll': 41,
         'cook': 11,
         'touch': 8,
         'age': 6,
         'tussle': 6,
         'ear': 2,
         'snarl': 4,
         'haired': 28,
         'hiss': 1,
         'growl': 6,
         'hide': 5,
         'toy': 1,
         'approach': 11,
         'cruise': 1,
         'trot': 15,
         'eat': 50,
         'leash': 5,
         'pull': 84,
         'sled': 56,
         'dogsled': 2,
         'mush': 3,
         'attach': 17,
         'join': 1,
         'red': 4,
         'bark': 17,
         'grab': 18,
         'observe': 5,
         'smile': 13,
         'talk': 15,
         'squat': 4,
         'face': 28,
         'show': 21,
         'allow': 3,
         'cover': 80,
         'swim': 125,
         'hang': 42,
         'trek': 2,
         'climb': 39,
         'drink': 22,
         'use': 18,
         'overlook': 5,
         'fetch': 45,
         'race': 69,
         'sell': 6,
         'emerge': 10,
         'come': 30,
         'strip': 18,
         'leave': 8,
         'camp': 2,
         'cross': 18,
         'drag': 5,
         'wad': 18,
         'aim': 3,
         'shoot': 3,
         'bed': 1,
         'seaweed': 2,
         'pick': 5,
         'wait': 20,
         'rummage': 1,
         'dress': 40,
         'lift': 4,
         'compete': 11,
         'tread': 5,
         'tag': 1,
         'slop': 1,
         'slant': 1,
         'collect': 1,
         'train': 23,
         'pad': 3,
         'attack': 13,
         'pose': 19,
         'pave': 4,
         'side': 7,
         'bound': 17,
         'spot': 18,
         'reveal': 1,
         'print': 2,
         'stir': 3,
         'bring': 7,
         'kick': 7,
         'bar': 11,
         'handle': 2,
         'knot': 2,
         'chew': 44,
         'beg': 6,
         'greet': 7,
         'sniff': 50,
         'enjoy': 20,
         'fence': 17,
         'buy': 4,
         'sunset': 2,
         'read': 11,
         'cut': 3,
         'pant': 2,
         'jog': 3,
         'teeth': 1,
         'cast': 6,
         'tether': 2,
         'work': 13,
         'find': 5,
         'gear': 2,
         'appear': 19,
         'crack': 1,
         'mix': 1,
         'stretch': 5,
         'shrubs': 1,
         'exit': 4,
         'asleep': 1,
         'relax': 6,
         'perform': 9,
         'reach': 13,
         'ask': 1,
         'rid': 28,
         'follow': 60,
         'vary': 2,
         'struggle': 1,
         'skin': 1,
         'clean': 4,
         'strain': 2,
         'dive': 6,
         'barbecue': 3,
         'bury': 4,
         'war': 1,
         'put': 9,
         'lick': 44,
         'explore': 3,
         'rail': 2,
         'lead': 26,
         'cord': 1,
         'pet': 29,
         'pink': 7,
         'cool': 1,
         'adopt': 2,
         'kiss': 10,
         'travel': 6,
         'drift': 1,
         'coat': 2,
         'interact': 8,
         'shape': 4,
         'cavort': 1,
         'hike': 3,
         'stop': 5,
         'pucker': 1,
         'happen': 2,
         'grapple': 1,
         'engage': 1,
         'hug': 6,
         'start': 2,
         'alert': 1,
         'break': 5,
         'step': 2,
         'investigate': 6,
         'muzzle': 19,
         'gallop': 3,
         'dig': 30,
         'tint': 2,
         'snuggle': 2,
         'place': 4,
         'scratch': 3,
         'contort': 1,
         'perch': 2,
         'clear': 1,
         'enclose': 2,
         'locate': 3,
         'fee': 2,
         'feed': 8,
         'herd': 10,
         'flower': 1,
         'head': 5,
         'lean': 11,
         'sail': 1,
         'direct': 1,
         'sideways': 1,
         'knit': 1,
         'slide': 6,
         'pass': 7,
         'seat': 7,
         'outrun': 1,
         'keep': 2,
         'bald': 2,
         'participate': 2,
         'set': 8,
         'operate': 1,
         'background': 1,
         'grind': 1,
         'hay': 1,
         'ski': 3,
         'patch': 1,
         'see': 15,
         'blue': 3,
         'wade': 3,
         'fire': 1,
         'legs': 3,
         'chain': 4,
         'pile': 1,
         'swing': 1,
         'lunge': 1,
         'waling': 1,
         'bind': 3,
         'wooded': 3,
         'roast': 2,
         'pounce': 5,
         'paw': 3,
         'brown': 3,
         'paint': 8,
         'base': 1,
         'hit': 2,
         'descend': 4,
         'lips': 1,
         'row': 1,
         'canoe': 1,
         'drop': 4,
         'harness': 2,
         'confront': 2,
         'towards': 1,
         'await': 2,
         'like': 2,
         'group': 1,
         'line': 7,
         'paddle': 5,
         'whilst': 5,
         'embrace': 1,
         'nurse': 2,
         'number': 1,
         'marble': 1,
         'focus': 2,
         'pay': 2,
         'pee': 4,
         'check': 7,
         'meet': 8,
         'contain': 1,
         'zigzag': 2,
         'rock': 2,
         'furry': 2,
         'bear': 9,
         'wrap': 4,
         'bath': 1,
         'pat': 2,
         'land': 1,
         'beside': 1,
         'stiffing': 1,
         'share': 1,
         'squirt': 9,
         'drive': 2,
         'weave': 2,
         'checker': 1,
         'space': 1,
         'toss': 3,
         'duck': 1,
         'bridge': 1,
         'kneel': 10,
         'butt': 1,
         'outstretched': 2,
         'poke': 3,
         'prance': 2,
         'mean': 1,
         'intend': 1,
         'high': 2,
         'balance': 3,
         'atop': 1,
         'spring': 1,
         'pour': 2,
         'huddle': 1,
         'roughhouse': 2,
         'guide': 5,
         'hop': 4,
         'receive': 3,
         'round': 5,
         'yawn': 2,
         'orange': 1,
         'blow': 3,
         'want': 3,
         'pillow': 1,
         'lap': 2,
         'ankle': 1,
         'shout': 1,
         'romp': 2,
         'surge': 1,
         'stride': 1,
         'march': 1,
         'complete': 2,
         'close': 3,
         'midair': 1,
         'win': 3,
         'return': 3,
         'behinds': 1,
         'smell': 7,
         'clap': 2,
         'mark': 4,
         'frolic': 3,
         'edge': 2,
         'divide': 1,
         'spread': 1,
         'park': 1,
         'lose': 2,
         'hose': 1,
         'tend': 2,
         'deflate': 4,
         'crawl': 1,
         'squeeze': 2,
         'sheep': 1,
         'howl': 4,
         'measure': 1,
         'cheek': 1,
         'nuzzle': 1,
         'nose': 5,
         'skate': 1,
         'pin': 3,
         'display': 2,
         'frisbee': 1,
         'bulge': 1,
         'enter': 4,
         'pooping': 1,
         'defecate': 1,
         'flap': 2,
         'flop': 1,
         'control': 2,
         'laugh': 4,
         'carpet': 2,
         'yell': 1,
         'drool': 2,
         'demonstrate': 2,
         'hunt': 3,
         'trail': 4,
         'hurdle': 1,
         'stroll': 2,
         'back': 1,
         'scale': 1,
         'fashion': 1,
         'discuss': 1,
         'pursue': 1,
         'ball': 3,
         'become': 1,
         'shock': 1,
         'kitten': 1,
         'nibble': 3,
         'gray': 1,
         'shore': 1,
         'advertise': 1,
         'urinate': 2,
         'multicolored': 3,
         'remain': 1,
         'ice': 1,
         'eye': 3,
         'dapple': 1,
         'beneath': 1,
         'silhouette': 1,
         'shed': 2,
         'link': 2,
         'helmet': 1,
         'rush': 2,
         'border': 1,
         'twist': 2,
         'shirt': 1,
         'corner': 1,
         'gnaw': 3,
         'entangle': 1,
         'counter': 1,
         'wither': 1,
         'tennis': 1,
         'rehearse': 1,
         'boys': 1,
         'gather': 7,
         'spark': 1,
         'snap': 1,
         'lop': 1,
         'examine': 5,
         'suck': 1,
         'circus': 1,
         'gesture': 1,
         'dance': 1,
         'bits': 2,
         'rip': 2,
         'tan': 1,
         'flank': 1,
         'airborne': 1,
         'muscle': 1,
         'dust': 1,
         'practice': 1,
         'carve': 1,
         'ignore': 2,
         'wake': 1,
         'beat': 1,
         'finish': 2,
         'sprint': 1,
         'encourage': 2,
         'begin': 4,
         'accompany': 6,
         'beach': 1,
         'press': 1,
         'nip': 1,
         'raise': 3,
         'fend': 1,
         'circumvent': 1,
         'clutch': 1,
         'peanut': 1,
         'rub': 3,
         'outcrop': 1,
         'lower': 1,
         'tease': 1,
         'rear': 3,
         'litter': 1,
         'parallel': 1,
         'scar': 1,
         'tangle': 1,
         'strike': 1,
         'tree': 2,
         'glide': 1,
         'cause': 2,
         'manicure': 2,
         'stroke': 1,
         'hood': 1,
         'match': 1,
         'grasp': 1,
         'hunch': 1,
         'include': 2,
         'circle': 2,
         'lounge': 1,
         'dinner': 2,
         'amaze': 1,
         'carying': 1,
         'light': 1,
         'coach': 1,
         'tilt': 1,
         'point': 1,
         'decorate': 2,
         'hump': 2,
         'overwhelm': 1,
         'exercise': 1,
         'entwine': 1,
         'groom': 1,
         'nestle': 1,
         'pop': 1,
         'stoop': 2,
         'mow': 1,
         'bare': 1,
         'rope': 1,
         'stuff': 2,
         'teach': 2,
         'sunshine': 1,
         'shin': 1,
         'ride': 2,
         'block': 1,
         'shave': 5,
         'recline': 1,
         'crash': 3,
         'chop': 2,
         'kindle': 1,
         'hurry': 1,
         'avoid': 1,
         'dangle': 1,
         'collide': 1,
         'mate': 1,
         'yellow': 2,
         'lasso': 1,
         'view': 2,
         'expose': 1,
         'seem': 3,
         'towns': 1,
         'threaten': 1,
         'blindfold': 1,
         'cock': 1,
         'mommy': 1,
         'admire': 1,
         'concern': 1,
         'inspect': 2,
         'propel': 1,
         'miss': 1,
         'judge': 3,
         'parade': 1,
         'vacation': 1,
         'extend': 2,
         'neck': 1,
         'dye': 1,
         'search': 2,
         'track': 1,
         'roam': 1,
         'abandon': 1,
         'rust': 1,
         'sip': 1,
         'let': 3,
         'deliver': 1,
         'acquaint': 1,
         'ring': 1,
         'melt': 1,
         'suspend': 1,
         'smoke': 1,
         'straight': 1,
         'surf': 3,
         'offer': 1,
         'realty': 1,
         'purchase': 1,
         'seek': 1,
         'cling': 1,
         'disgust': 1,
         'scrunch': 1,
         'anticipate': 1,
         'nap': 1,
         'feature': 1,
         'hotdog': 1,
         'cart': 1,
         'write': 1,
         'friend': 1,
         'buns': 1,
         'serve': 1,
         'love': 2,
         'pause': 1,
         'say': 2,
         'adorn': 1,
         'surprise': 1,
         'beard': 1,
         'cradle': 1,
         'hand': 2,
         'forage': 1,
         'pine': 1,
         'chill': 1,
         'flip': 1,
         'medium': 1,
         'distract': 2,
         'wave': 1,
         'label': 1,
         'call': 1,
         'peek': 1,
         'fold': 1,
         'slouch': 1,
         'skip': 1,
         'bounce': 1,
         'bundle': 1,
         'snowshoe': 1,
         'change': 1,
         'socialize': 1,
         'shovel': 1,
         'poise': 1,
         'bratwurst': 1,
         'build': 2,
         'ting': 1,
         'load': 1,
         'disqualify': 1,
         'rollerblade': 2,
         'legged': 1,
         'sky': 1,
         'appreciate': 1,
         'draw': 3,
         'sketch': 2,
         'camouflage': 1,
         'listen': 1,
         'punch': 1,
         'sunglasses': 1,
         'reflect': 1})

# Step 3 Keyword analysis

In [ ]:
# @title 3-1

## Generate co-occurrence pairs
co_occurrence = []
for words_per_text in words:
    for i in range(len(words_per_text)):
        for j in range(i + 1, len(words_per_text)):  # Avoid self-pairing
            co_occurrence.append((words_per_text[i], words_per_text[j]))
co_occurrence

[('color', 'play'),
 ('sleep', 'sit'),
 ('lay', 'tie'),
 ('lay', 'hold'),
 ('lay', 'sit'),
 ('hold', 'sit'),
 ('run', 'surround'),
 ('stand', 'turn'),
 ('leap', 'fall'),
 ('leap', 'fall'),
 ('wear', 'grill'),
 ('wear', 'hold'),
 ('grill', 'hold'),
 ('wear', 'hotdogs'),
 ('hold', 'grill'),
 ('prepare', 'catch'),
 ('catch', 'fly'),
 ('try', 'catch'),
 ('leap', 'catch'),
 ('carry', 'walk'),
 ('jump', 'catch'),
 ('stand', 'sit'),
 ('attempt', 'catch'),
 ('jump', 'catch'),
 ('hold', 'throw'),
 ('rest', 'open'),
 ('run', 'grass'),
 ('get', 'spray'),
 ('jump', 'catch'),
 ('catch', 'watch'),
 ('stick', 'run'),
 ('hold', 'splash'),
 ('hold', 'fill'),
 ('splash', 'fill'),
 ('run', 'carry'),
 ('create', 'run'),
 ('dry', 'shake'),
 ('wash', 'size'),
 ('wash', 'secure'),
 ('size', 'secure'),
 ('hold', 'soap'),
 ('run', 'bite'),
 ('run', 'play'),
 ('stand', 'roll'),
 ('jump', 'catch'),
 ('jump', 'catch'),
 ('color', 'jump'),
 ('color', 'leap'),
 ('touch', 'look'),
 ('age', 'cook'),
 ('leap', 'surround'),
 ('jump', 'catch'),
 ('leap', 'catch'),
 ('play', 'bite'),
 ('bite', 'ear'),
 ('bite', 'ear'),
 ('wear', 'run'),
 ('wear', 'chase'),
 ('run', 'chase'),
 ('snarl', 'haired'),
 ('hiss', 'try'),
 ('hiss', 'get'),
 ('try', 'get'),
 ('growl', 'hide'),
 ('toy', 'hide'),
 ('eat', 'leash'),
 ('sit', 'hold'),
 ('wear', 'turn'),
 ('wear', 'pull'),
 ('pull', 'sled'),
 ('pull', 'sled'),
 ('dogsled', 'pull'),
 ('pull', 'sled'),
 ('run', 'look'),
 ('take', 'jump'),
 ('take', 'grab'),
 ('jump', 'grab'),
 ('jump', 'attempt'),
 ('jump', 'catch'),
 ('attempt', 'catch'),
 ('crouch', 'smile'),
 ('crouch', 'sit'),
 ('smile', 'sit'),
 ('talk', 'sit'),
 ('squat', 'face'),
 ('squat', 'hold'),
 ('face', 'hold'),
 ('play', 'fill'),
 ('carry', 'swim'),
 ('swim', 'hold'),
 ('run', 'hang'),
 ('pull', 'sled'),
 ('sled', 'trek'),
 ('pull', 'sled'),
 ('run', 'hang'),
 ('go', 'watch'),
 ('walk', 'look'),
 ('walk', 'look'),
 ('bend', 'try'),
 ('bend', 'drink'),
 ('try', 'drink'),
 ('jump', 'swim'),
 ('jump', 'retrieve'),
 ('jump', 'float'),
 ('swim', 'retrieve'),
 ('swim', 'float'),
 ('retrieve', 'float'),
 ('hold', 'walk'),
 ('walk', 'use'),
 ('run', 'watch'),
 ('race', 'look'),
 ('come', 'strip'),
 ('leave', 'strip'),
 ('carry', 'camp'),
 ('run', 'carry'),
 ('run', 'hold'),
 ('wear', 'run'),
 ('wear', 'run'),
 ('walk', 'carry'),
 ('drag', 'dry'),
 ('stand', 'look'),
 ('stand', 'walk'),
 ('look', 'walk'),
 ('aim', 'shoot'),
 ('aim', 'stand'),
 ('shoot', 'look'),
 ('lie', 'bed'),
 ('carry', 'seaweed'),
 ('hold', 'bend'),
 ('hold', 'look'),
 ('bend', 'look'),
 ('bend', 'pick'),
 ('wait', 'rummage'),
 ('run', 'carry'),
 ('play', 'run'),
 ('lift', 'stand'),
 ('lift', 'strip'),
 ('stand', 'strip'),
 ('shake', 'play'),
 ('shake', 'get'),
 ('play', 'splash'),
 ('play', 'catch'),
 ('jump', 'catch'),
 ('wad', 'hold'),
 ('jump', 'catch'),
 ('color', 'catch'),
 ('color', 'throw'),
 ('catch', 'throw'),
 ('leap', 'play'),
 ('slop', 'overlook'),
 ('climb', 'slant'),
 ('jump', 'catch'),
 ('color', 'run'),
 ('hold', 'try'),
 ('hold', 'take'),
 ('hold', 'look'),
 ('try', 'take'),
 ('try', 'look'),
 ('take', 'look'),
 ('wear', 'wear'),
 ('wear', 'hold'),
 ('wear', 'hold'),
 ('get', 'fight'),
 ('emerge', 'collect'),
 ('wear', 'drag'),
 ('run', 'hold'),
 ('walk', 'try'),
 ('walk', 'bite'),
 ('try', 'bite'),
 ('wear', 'train'),
 ('jump', 'bite'),
 ('jump', 'pad'),
 ('bite', 'pad'),
 ('train', 'attack'),
 ('lay', 'look'),
 ('hold', 'sit'),
 ('color', 'wrestle'),
 ('tussle', 'pave'),
 ('run', 'side'),
 ('run', 'color'),
 ('run', 'carry'),
 ('side', 'color'),
 ('side', 'carry'),
 ('color', 'carry'),
 ('hold', 'walk'),
 ('run', 'cover'),
 ('color', 'jump'),
 ('run', 'play'),
 ('sit', 'hold'),
 ('sit', 'look'),
 ('hold', 'look'),
 ('hold', 'sit'),
 ('hold', 'overlook'),
 ('sit', 'overlook'),
 ('walk', 'surround'),
 ('fall', 'look'),
 ('spot', 'look'),
 ('try', 'bite'),
 ('reveal', 'bite'),
 ('look', 'grab'),
 ('bite', 'print'),
 ('try', 'catch'),
 ('run', 'make'),
 ('stick', 'run'),
 ('wear', 'run'),
 ('wear', 'run'),
 ('run', 'wear'),
 ('color', 'jump'),
 ('bring', 'run'),
 ('walk', 'fall'),
 ('lift', 'grab'),
 ('lift', 'hang'),
 ('grab', 'hang'),
 ('handle', 'knot'),
 ('chew', 'watch'),
 ('run', 'swim'),
 ('lie', 'look'),
 ('try', 'catch'),
 ('try', 'catch'),
 ('try', 'catch'),
 ('jump', 'walk'),
 ('jump', 'wear'),
 ('enjoy', 'play'),
 ('spot', 'jump'),
 ('trot', 'fence'),
 ('jump', 'catch'),
 ('buy', 'jump'),
 ('buy', 'catch'),
 ('jump', 'catch'),
 ('leap', 'catch'),
 ('catch', 'sunset'),
 ('read', 'eat'),
 ('sit', 'eat'),
 ('sniff', 'cut'),
 ('sniff', 'cut'),
 ('jog', 'hang'),
 ('run', 'hang'),
 ('open', 'teeth'),
 ('open', 'show'),
 ('open', 'hang'),
 ('teeth', 'show'),
 ('teeth', 'hang'),
 ('show', 'hang'),
 ('make', 'face'),
 ('make', 'play'),
 ('face', 'play'),
 ('jump', 'catch'),
 ('jump', 'cast'),
 ('catch', 'cast'),
 ('look', 'catch'),
 ('lie', 'tether'),
 ('wear', 'walk'),
 ('stand', 'watch'),
 ('run', 'wear'),
 ('run', 'red'),
 ('wear', 'red'),
 ('work', 'observe'),
 ('walk', 'find'),
 ('dress', 'gear'),
 ('dress', 'walk'),
 ('gear', 'walk'),
 ('dress', 'wear'),
 ('dress', 'stand'),
 ('dress', 'dress'),
 ('dress', 'look'),
 ('wear', 'stand'),
 ('wear', 'dress'),
 ('wear', 'look'),
 ('stand', 'dress'),
 ('stand', 'look'),
 ('dress', 'look'),
 ('stand', 'appear'),
 ('stand', 'walk'),
 ('walk', 'crack'),
 ('stand', 'hold'),
 ('stand', 'jump'),
 ('hold', 'jump'),
 ('get', 'throw'),
 ('get', 'wait'),
 ('throw', 'wait'),
 ('wear', 'take'),
 ('wear', 'mix'),
 ('take', 'mix'),
 ('take', 'sit'),
 ('stretch', 'sit'),
 ('color', 'look'),
 ('look', 'sit'),
 ('look', 'shrubs'),
 ('sit', 'shrubs'),
 ('asleep', 'sit'),
 ('sniff', 'sleep'),
 ('sniff', 'sit'),
 ('sleep', 'sit'),
 ('run', 'cover'),
 ('wear', 'walk'),
 ('perform', 'observe'),
 ('sniff', 'sniff'),
 ('ask', 'give'),
 ('look', 'catch'),
 ('vary', 'run'),
 ('star', 'sleep'),
 ('struggle', 'hold'),
 ('skin', 'walk'),
 ('skin', 'leash'),
 ('walk', 'leash'),
 ('show', 'walk'),
 ('try', 'reach'),
 ('try', 'pull'),
 ('reach', 'pull'),
 ('strain', 'walk'),
 ('strain', 'walk'),
 ('climb', 'surround'),
 ('run', 'cover'),
 ('leap', 'try'),
 ('leap', 'fetch'),
 ('leap', 'float'),
 ('try', 'fetch'),
 ('try', 'float'),
 ('fetch', 'float'),
 ('dive', 'get'),
 ('age', 'wear'),
 ('age', 'cook'),
 ('wear', 'cook'),
 ('jump', 'catch'),
 ('catch', 'jump'),
 ('jump', 'catch'),
 ('run', 'carry'),
 ('run', 'hold'),
 ('carry', 'run'),
 ('carry', 'wad'),
 ('war', 'run'),
 ('bite', 'stand'),
 ('lick', 'fall'),
 ('size', 'sniff'),
 ('talk', 'cord'),
 ('talk', 'pet'),
 ('cord', 'pet'),
 ('wear', 'talk'),
 ('talk', 'pet'),
 ('talk', 'stand'),
 ('stand', 'shake'),
 ('shake', 'come'),
 ('pull', 'play'),
 ('fight', 'pink'),
 ('haired', 'walk'),
 ('walk', 'use'),
 ('wear', 'lick'),
 ('get', 'lick'),
 ('lie', 'travel'),
 ('look', 'look'),
 ('stand', 'look'),
 ('hold', 'wear'),
 ('sit', 'hold'),
 ('hold', 'smile'),
 ('turn', 'allow'),
 ('turn', 'drink'),
 ('allow', 'drink'),
 ('attempt', 'drink'),
 ('coat', 'growl'),
 ('coat', 'jump'),
 ('growl', 'jump'),
 ('stand', 'snarl'),
 ('stand', 'stand'),
 ('snarl', 'stand'),
 ('stand', 'interact'),
 ('jump', 'catch'),
 ('fight', 'bite'),
 ('lead', 'climb'),
 ('lead', 'cover'),
 ('climb', 'cover'),
 ('try', 'catch'),
 ('run', 'throw'),
 ('carry', 'walk'),
 ('run', 'hold'),
 ('walk', 'carry'),
 ('catch', 'stand'),
 ('jump', 'catch'),
 ('jump', 'catch'),
 ('run', 'catch'),
 ('run', 'wear'),
 ('grapple', 'stand'),
 ('play', 'fight'),
 ('wrestle', 'hug'),
 ('wear', 'play'),
 ('wear', 'tussle'),
 ('wear', 'run'),
 ('race', 'run'),
 ('race', 'start'),
 ('run', 'start'),
 ('jump', 'catch'),
 ('jump', 'get'),
 ('bite', 'lie'),
 ('lay', 'bite'),
 ('walk', 'bite'),
 ('color', 'alert'),
 ('color', 'hold'),
 ('color', 'color'),
 ('alert', 'hold'),
 ('alert', 'color'),
 ('hold', 'color'),
 ('walk', 'stand'),
 ('sit', 'hold'),
 ('sit', 'investigate'),
 ('hold', 'investigate'),
 ('pose', 'sit'),
 ('interact', 'hold'),
 ('wear', 'run'),
 ('muzzle', 'leap'),
 ('dig', 'find'),
 ('color', 'run'),
 ('run', 'carry'),
 ('color', 'walk'),
 ('lick', 'wear'),
 ('lick', 'tint'),
 ('wear', 'tint'),
 ('lick', 'wear'),
 ('roll', 'scratch'),
 ('shake', 'get'),
 ('shake', 'contort'),
 ('get', 'contort'),
 ('look', 'sit'),
 ('look', 'perch'),
 ('leap', 'run'),
 ('jump', 'clear'),
 ('walk', 'run'),
 ('haired', 'run'),
 ('spot', 'run'),
 ('run', 'wear'),
 ('wear', 'run'),
 ('wear', 'run'),
 ('wear', 'run'),
 ('tread', 'locate'),
 ('crouch', 'prepare'),
 ('crouch', 'fee'),
 ('prepare', 'fee'),
 ('feed', 'look'),
 ('feed', 'herd'),
 ('lay', 'flower'),
 ('lie', 'head'),
 ('hang', 'run'),
 ('run', 'sail'),
 ('walk', 'enjoy'),
 ('wear', 'carry'),
 ('make', 'catch'),
 ('sideways', 'catch'),
 ('age', 'sit'),
 ('age', 'wear'),
 ('age', 'prepare'),
 ('age', 'play'),
 ('sit', 'wear'),
 ('sit', 'prepare'),
 ('sit', 'play'),
 ('wear', 'prepare'),
 ('wear', 'play'),
 ('prepare', 'play'),
 ('hold', 'wear'),
 ('hold', 'wear'),
 ('wear', 'wear'),
 ('dress', 'sit'),
 ('wear', 'play'),
 ('wear', 'knit'),
 ('wear', 'slide'),
 ('wear', 'sled'),
 ('wear', 'run'),
 ('knit', 'slide'),
 ('knit', 'sled'),
 ('knit', 'run'),
 ('slide', 'sled'),
 ('slide', 'run'),
 ('sled', 'run'),
 ('rid', 'sled'),
 ('rid', 'run'),
 ('rid', 'side'),
 ('sled', 'run'),
 ('sled', 'side'),
 ('run', 'side'),
 ('carry', 'walk'),
 ('carry', 'cover'),
 ('walk', 'cover'),
 ('jump', 'catch'),
 ('jump', 'catch'),
 ('attempt', 'catch'),
 ('jump', 'throw'),
 ('jump', 'look'),
 ('jump', 'pass'),
 ('look', 'pass'),
 ('jump', 'wait'),
 ('jump', 'catch'),
 ('jump', 'throw'),
 ('wait', 'catch'),
 ('wait', 'throw'),
 ('catch', 'throw'),
 ('wear', 'seat'),
 ('wear', 'seat'),
 ('wear', 'hold'),
 ('seat', 'hold'),
 ('hold', 'sit'),
 ('try', 'run'),
 ('try', 'bury'),
 ('run', 'bury'),
 ('try', 'outrun'),
 ('turn', 'lead'),
 ('jump', 'get'),
 ('run', 'jump'),
 ('wear', 'run'),
 ('walk', 'tie'),
 ('play', 'keep'),
 ('give', 'chew'),
 ('color', 'climb'),
 ('run', 'follow'),
 ('run', 'set'),
 ('swim', 'splash'),
 ('appear', 'operate'),
 ('lay', 'show'),
 ('lay', 'break'),
 ('show', 'break'),
 ('climb', 'background'),
 ('climb', 'break'),
 ('background', 'break'),
 ('run', 'catch'),
 ('run', 'follow'),
 ('run', 'jump'),
 ('run', 'walk'),
 ('jump', 'walk'),
 ('run', 'walk'),
 ('surround', 'run'),
 ('run', 'color'),
 ('try', 'get'),
 ('stand', 'surround'),
 ('jump', 'wear'),
 ('hold', 'beg'),
 ('pull', 'cover'),
 ('play', 'cover'),
 ('run', 'patch'),
 ('run', 'hang'),
 ('attempt', 'catch'),
 ('run', 'catch'),
 ('catch', 'fly'),
 ('run', 'see'),
 ('swim', 'hold'),
 ('leap', 'run'),
 ('run', 'watch'),
 ('wade', 'watch'),
 ('look', 'stand'),
 ('hold', 'rail'),
 ('dress', 'stand'),
 ('jump', 'hold'),
 ('run', 'jump'),
 ('jump', 'hold'),
 ('stand', 'stand'),
 ('jump', 'wear'),
 ('stand', 'legs'),
 ('jump', 'coat'),
 ('sit', 'look'),
 ('sit', 'look'),
 ('color', 'run'),
 ('carry', 'run'),
 ('wear', 'look'),
 ('attempt', 'chew'),
 ('run', 'cover'),
 ('run', 'hold'),
 ('cover', 'hold'),
 ('play', 'carry'),
 ('run', 'carry'),
 ('run', 'stand'),
 ('make', 'pile'),
 ('jump', 'catch'),
 ('stand', 'cover'),
 ('stand', 'hold'),
 ('cover', 'hold'),
 ('swing', 'look'),
 ('run', 'run'),
 ('dress', 'run'),
 ('wear', 'look'),
 ('look', 'make'),
 ('wear', 'kick'),
 ('wear', 'stand'),
 ('kick', 'stand'),
 ('play', 'lay'),
 ('wear', 'hold'),
 ('look', 'wear'),
 ('run', 'wooded'),
 ('strip', 'eat'),
 ('wear', 'hold'),
 ('wear', 'roast'),
 ('hold', 'roast'),
 ('run', 'run'),
 ('run', 'play'),
 ('wear', 'play'),
 ('wear', 'get'),
 ('wear', 'pounce'),
 ('run', 'cover'),
 ('run', 'leave'),
 ('run', 'cover'),
 ('leave', 'cover'),
 ('run', 'fall'),
 ('color', 'walk'),
 ('run', 'open'),
 ('wear', 'run'),
 ('wear', 'carry'),
 ('run', 'carry'),
 ('carry', 'run'),
 ('run', 'carry'),
 ('brown', 'play'),
 ('hold', 'paint'),
 ('paint', 'base'),
 ('hold', 'paint'),
 ('wear', 'sit'),
 ('wear', 'pet'),
 ('wear', 'wear'),
 ('sit', 'pet'),
 ('sit', 'wear'),
 ('pet', 'wear'),
 ('sit', 'locate'),
 ('sit', 'play'),
 ('locate', 'play'),
 ('look', 'investigate'),
 ('look', 'size'),
 ('color', 'wear'),
 ('color', 'shake'),
 ('wear', 'shake'),
 ('wear', 'shake'),
 ('wear', 'run'),
 ('chase', 'snow'),
 ('enjoy', 'play'),
 ('bark', 'run'),
 ('descend', 'bar'),
 ('stand', 'look'),
 ('jump', 'catch'),
 ('leap', 'catch'),
 ('color', 'attach'),
 ('color', 'sit'),
 ('attach', 'sit'),
 ('sit', 'stick'),
 ('hold', 'haired'),
 ('hold', 'stand'),
 ('smile', 'hold'),
 ('see', 'run'),
 ('lips', 'run'),
 ('walk', 'lick'),
 ('run', 'hang'),
 ('run', 'play'),
 ('run', 'side'),
 ('wear', 'sit'),
 ('run', 'catch'),
 ('appear', 'stand'),
 ('appear', 'legs'),
 ('appear', 'jump'),
 ('stand', 'legs'),
 ('stand', 'jump'),
 ('legs', 'jump'),
 ('try', 'play'),
 ('swim', 'bite'),
 ('play', 'bound'),
 ('play', 'carry'),
 ('hold', 'run'),
 ('play', 'fence'),
 ('harness', 'pull'),
 ('sled', 'see'),
 ('lay', 'look'),
 ('run', 'play'),
 ('await', 'kick'),
 ('await', 'retrieve'),
 ('kick', 'retrieve'),
 ('lay', 'strip'),
 ('try', 'chew'),
 ('wear', 'run'),
 ('bound', 'cover'),
 ('run', 'cover'),
 ('bar', 'run'),
 ('jump', 'wear'),
 ('bite', 'fall'),
 ('hold', 'walk'),
 ('walk', 'hold'),
 ('take', 'line'),
 ('come', 'face'),
 ('look', 'stand'),
 ('jump', 'whilst'),
 ('jump', 'try'),
 ('jump', 'catch'),
 ('whilst', 'try'),
 ('whilst', 'catch'),
 ('try', 'catch'),
 ('jump', 'catch'),
 ('catch', 'fly'),
 ('shake', 'get'),
 ('run', 'chase'),
 ('chase', 'hold'),
 ('run', 'chase'),
 ('run', 'chase'),
 ('jump', 'play'),
 ('jump', 'break'),
 ('play', 'break'),
 ('trot', 'carry'),
 ('pull', 'wear'),
 ('sled', 'sled'),
 ('embrace', 'hold'),
 ('embrace', 'look'),
 ('hold', 'look'),
 ('give', 'kiss'),
 ('kiss', 'hold'),
 ('walk', 'play'),
 ('walk', 'carry'),
 ('run', 'attach'),
 ('play', 'fence'),
 ('run', 'throw'),
 ('jump', 'turn'),
 ('run', 'wear'),
 ('wear', 'run'),
 ('color', 'jump'),
 ('watch', 'run'),
 ('run', 'wear'),
 ('jump', 'cover'),
 ('wear', 'focus'),
 ('pay', 'dress'),
 ('pee', 'sniff'),
 ('pee', 'walk'),
 ('sniff', 'walk'),
 ('growl', 'wear'),
 ('color', 'play'),
 ('color', 'color'),
 ('color', 'fence'),
 ('play', 'color'),
 ('play', 'fence'),
 ('color', 'fence'),
 ('run', 'fence'),
 ('get', 'soak'),
 ('get', 'play'),
 ('soak', 'play'),
 ('race', 'run'),
 ('run', 'carry'),
 ('sit', 'hold'),
 ('wear', 'run'),
 ('wear', 'run'),
 ('wear', 'run'),
 ('play', 'contain'),
 ('run', 'wear'),
 ('wear', 'run'),
 ('wear', 'jump'),
 ('run', 'jump'),
 ('wear', 'jump'),
 ('train', 'zigzag'),
 ('go', 'look'),
 ('play', 'run'),
 ('carry', 'run'),
 ('carry', 'lie'),
 ('run', 'lie'),
 ('run', 'hold'),
 ('play', 'rock'),
 ('fight', 'rock'),
 ('color', 'go'),
 ('color', 'bite'),
 ('go', 'bite'),
 ('furry', 'fight'),
 ('stand', 'race'),
 ('run', 'fly'),
 ('color', 'chase'),
 ('run', 'get'),
 ('run', 'chase'),
 ('run', 'make'),
 ('hold', 'keep'),
 ('jump', 'stand'),
 ('run', 'wear'),
 ('swim', 'retrieve'),
 ('wear', 'spot'),
 ('sit', 'wrap'),
 ('bath', 'wrap'),
 ('use', 'dry'),
 ('pat', 'dry'),
 ('pat', 'give'),
 ('dry', 'give'),
 ('land', 'try'),
 ('land', 'get'),
 ('try', 'get'),
 ('wear', 'carry'),
 ('wear', 'play'),
 ('wear', 'hold'),
 ('run', 'come'),
 ('follow', 'beside'),
 ('prepare', 'throw'),
 ('jump', 'catch'),
 ('jump', 'catch'),
 ('jump', 'catch'),
 ('wear', 'dig'),
 ('run', 'chase'),
 ('run', 'catch'),
 ('hold', 'run'),
 ('hold', 'chase'),
 ('run', 'chase'),
 ('try', 'bite'),
 ('try', 'come'),
 ('bite', 'come'),
 ('wear', 'play'),
 ('prepare', 'bite'),
 ('jump', 'catch'),
 ('muzzle', 'jump'),
 ('move', 'checker'),
 ('wear', 'dive'),
 ('swim', 'wad'),
 ('color', 'play'),
 ('sit', 'give'),
 ('sit', 'wear'),
 ('give', 'wear'),
 ('haired', 'sit'),
 ('jump', 'fly'),
 ('stick', 'jump'),
 ('leap', 'fall'),
 ('leap', 'fall'),
 ('size', 'play'),
 ('run', 'space'),
 ('run', 'pave'),
 ('catch', 'throw'),
 ('fly', 'throw'),
 ('catch', 'stand'),
 ('catch', 'watch'),
 ('stand', 'watch'),
 ('sit', 'watch'),
 ('sit', 'catch'),
 ('sit', 'stand'),
 ('sit', 'look'),
 ('watch', 'catch'),
 ('watch', 'stand'),
 ('watch', 'look'),
 ('catch', 'stand'),
 ('catch', 'look'),
 ('stand', 'look'),
 ('duck', 'fly'),
 ('duck', 'fetch'),
 ('fly', 'fetch'),
 ('wear', 'hold'),
 ('wear', 'wear'),
 ('hold', 'wear'),
 ('crouch', 'hold'),
 ('hold', 'jump'),
 ('haired', 'play'),
 ('run', 'fence'),
 ('run', 'surround'),
 ('fence', 'surround'),
 ('eat', 'sit'),
 ('carry', 'jump'),
 ('try', 'jump'),
 ('hold', 'jump'),
 ('wear', 'stand'),
 ('stand', 'bridge'),
 ('stand', 'look'),
 ('spot', 'run'),
 ('run', 'look'),
 ('throw', 'catch'),
 ('throw', 'catch'),
 ('give', 'jump'),
 ('walk', 'cover'),
 ('climb', 'follow'),
 ('climb', 'follow'),
 ('run', 'run'),
 ('wear', 'bear'),
 ('wear', 'sit'),
 ('bear', 'sit'),
 ('carry', 'run'),
 ('look', 'stand'),
 ('run', 'follow'),
 ('kneel', 'butt'),
 ('wear', 'run'),
 ('wear', 'run'),
 ('cross', 'fall'),
 ('cross', 'outstretched'),
 ('fall', 'outstretched'),
 ('cross', 'make'),
 ('cross', 'fall'),
 ('make', 'fall'),
 ('look', 'chase'),
 ('strip', 'run'),
 ('try', 'bite'),
 ('mean', 'run'),
 ('lay', 'lick'),
 ('sniff', 'lie'),
 ('lay', 'sniff'),
 ('sniff', 'lie'),
 ('sniff', 'lie'),
 ('prepare', 'throw'),
 ('prepare', 'intend'),
 ('prepare', 'fetch'),
 ('throw', 'intend'),
 ('throw', 'fetch'),
 ('intend', 'fetch'),
 ('throw', 'chase'),
 ('run', 'play'),
 ('look', 'throw'),
 ('wait', 'throw'),
 ('adopt', 'size'),
 ('lie', 'read'),
 ('read', 'roll'),
 ('read', 'look'),
 ('jump', 'catch'),
 ('high', 'get'),
 ('jump', 'catch'),
 ('throw', 'fetch'),
 ('throw', 'whilst'),
 ('fetch', 'whilst'),
 ('stand', 'throw'),
 ('throw', 'watch'),
 ('try', 'catch'),
 ('try', 'catch'),
 ('color', 'run'),
 ('run', 'stir'),
 ('run', 'catch'),
 ('attempt', 'catch'),
 ('leap', 'catch'),
 ('try', 'catch'),
 ('catch', 'follow'),
 ('play', 'catch'),
 ('run', 'jump'),
 ('stand', 'take'),
 ('run', 'lie'),
 ('jump', 'see'),
 ('watch', 'leap'),
 ('run', 'look'),
 ('hold', 'pour'),
 ('hold', 'drink'),
 ('pour', 'drink'),
 ('hold', 'drink'),
 ('drink', 'squirt'),
 ('hold', 'drink'),
 ('wear', 'run'),
 ('participate', 'wear'),
 ('wear', 'move'),
 ('wear', 'pad'),
 ('wear', 'bite'),
 ('pad', 'bite'),
 ('wear', 'bite'),
 ('train', 'attack'),
 ('prepare', 'herd'),
 ('shake', 'look'),
 ('color', 'roughhouse'),
 ('play', 'fight'),
 ('size', 'run'),
 ('lean', 'pet'),
 ('bend', 'touch'),
 ('run', 'jump'),
 ('wear', 'lay'),
 ('wear', 'chew'),
 ('lay', 'chew'),
 ('lie', 'chew'),
 ('splash', 'try'),
 ('splash', 'catch'),
 ('try', 'catch'),
 ('try', 'bite'),
 ('run', 'dress'),
 ('run', 'observe'),
 ('hop', 'throw'),
 ('hop', 'receive'),
 ('throw', 'receive'),
 ('wear', 'stand'),
 ('chase', 'jump'),
 ('cover', 'play'),
 ('walk', 'carry'),
 ('run', 'hold'),
 ('swim', 'carry'),
 ('walk', 'stand'),
 ('cross', 'look'),
 ('run', 'carry'),
 ('run', 'look'),
 ('carry', 'look'),
 ('walk', 'rest'),
 ('walk', 'put'),
 ('run', 'hang'),
 ('wear', 'stand'),
 ('hold', 'catch'),
 ('play', 'make'),
 ('wear', 'look'),
 ('wear', 'see'),
 ('wear', 'catch'),
 ('look', 'see'),
 ('look', 'catch'),
 ('see', 'catch'),
 ('stand', 'sit'),
 ('stand', 'watch'),
 ('stand', 'catch'),
 ('sit', 'watch'),
 ('sit', 'catch'),
 ('watch', 'catch'),
 ('catch', 'face'),
 ('leap', 'catch'),
 ('leap', 'orange'),
 ('catch', 'orange'),
 ('leap', 'catch'),
 ('run', 'stand'),
 ('run', 'set'),
 ('play', 'fight'),
 ('run', 'bark'),
 ('try', 'get'),
 ('try', 'get'),
 ('run', 'leave'),
 ('walk', 'splash'),
 ('fly', 'prepare'),
 ('fly', 'catch'),
 ('prepare', 'catch'),
 ('jump', 'meet'),
 ('wad', 'hold'),
 ('throw', 'fetch'),
 ('get', 'throw'),
 ...]

In [ ]:
# @title 3-2

## Create a frequency table for co-occurrence pairs
word_pairs = pd.DataFrame(co_occurrence, columns=["word1", "word2"])
word_pairs["frequency"] = 1
word_frequency_df = word_pairs.groupby(["word1", "word2"], as_index=False).sum()
word_frequency_df

          word1  word2  frequency
0      acquaint    sit          1
1         adopt   size          1
2         adorn   pull          1
3     advertise  stand          1
4           age   bald          1
...         ...    ...        ...
1772       wrap   walk          1
1773    wrestle  cover          1
1774    wrestle  fence          1
1775    wrestle    hug          1
1776    wrestle    run          1

[1777 rows x 3 columns]

In [ ]:
# @title 3-3

## Filter pairs based on minimum frequency
filtered_pairs = word_frequency_df[word_frequency_df["frequency"] >= 5]
filtered_pairs

        word1   word2  frequency
13        age    wear          5
53    attempt   catch          8
153     carry   cover          5
155     carry  follow          6
162     carry     run         11
...       ...     ...        ...
1742     wear   stand         22
1744     wear   strip          6
1746     wear    take          5
1756     wear    walk         26
1757     wear    wear          9

[92 rows x 3 columns]

In [ ]:
# @title 3-4

## Get keywords
G_pos = nx.Graph()
for _, row in filtered_pairs.iterrows():
    G_pos.add_edge(row["word1"], row["word2"], weight=row["frequency"])

## Calculate centrality measures
dgr = nx.degree_centrality(G_pos)  # Degree centrality

## Sort centrality measures
sorted_dgr = sorted(dgr.items(), key=operator.itemgetter(1), reverse=True)

## Print top keywords based on centrality
print("** Degree Centrality **")
for x in range(min(10, len(sorted_dgr))):  # Print top 10 or fewer
    print(sorted_dgr[x])

** Degree Centrality **
('run', 0.5238095238095237)
('wear', 0.30952380952380953)
('hold', 0.26190476190476186)
('walk', 0.23809523809523808)
('stand', 0.23809523809523808)
('catch', 0.19047619047619047)
('jump', 0.19047619047619047)
('sit', 0.16666666666666666)
('look', 0.14285714285714285)
('play', 0.11904761904761904)

# Step 4 Semantic network analysis

In [ ]:
# @title 4-1

## Build the graph
network = nx.Graph()
for index, row in filtered_pairs.iterrows():
    network.add_edge(row['word1'], row['word2'], frequency=row['frequency'])

## Community detection
communities = community_louvain.best_partition(network)

## Create a DataFrame for communities
communities_df = pd.DataFrame(list(communities.items()), columns=['Node', 'Community'])
community_groups = communities_df.groupby('Community')['Node'].apply(list).reset_index()

## Analyze verb communities
for _, row in community_groups.iterrows():
    comm_id = row['Community']
    nodes = row['Node']
    print(f"\nCommunity {comm_id} ({len(nodes)} verbs):")
    print(f"  Verbs: {', '.join(nodes[:10])}")

In [ ]:
# @title 4-2

## Visualize semantic network
plt.figure(figsize = (150,100)); plt.axis('off')


# Assign colors for communities
colors = ['tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan', 'tab:blue', 'tab:orange',
          'tab:green', 'tab:red', 'tab:purple', 'tab:black', 'tab:lightgray']
color_map = [colors[communities[node]] for node in network]


# Set the frequency attribute for each node
for i in list(network.nodes()):
    network.nodes[i]['counter_unigram'] = counter_unigram[i]


# Set size of node as a list of frequency of words
node_size = [4000 * nx.get_node_attributes(network, 'counter_unigram')[v] for v in network]

nx.draw_networkx(network, font_size = 50,
                 node_color = color_map, alpha = 0.8, node_size = node_size,
                 with_labels = True,
                 edge_color ='.5', cmap = plt.cm.Blues)